### ISSUE TITLE
about Y

### ISSUE THREAD

**Issue by kkfkk** [catalina17/XFlow#2]
Hi Catalina, it is glad to see your codes. Wonderful. But I have a few questions.
1 digits_data.py What is Y nad P? and why you set Y = np.empty(shape=(total,), dtype=np.int) and P = np.empty(shape=(total,), dtype=np.dtype('a16')) as an array. 
2 Currently, I want to use your code for audio and image classification. How could I update code in digits_data.py? Because you use sliding window for short video? many thanks.

**Comment by catalina17** [comment]
Hi,

For each of the samples in the train/test sets, Y contains the label and P the person from which the sample came from. They are arrays because they hold e.g. len(train) samples each for the train set.

I think you can simply create another data loader which produces tuples of (audio_vector_for_all_timesteps, image_array, label, person) for each sample, or corresponding arrays across all samples. You might need to update the models or use others, since these exploit temporal correlations across modalities.
